### PR TITLE
Update it.po

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by albanobattistella** [comment]
> please rebase and don't forget to add yourself as translator

HI,
I add myself as translator.
rebase?

**Comment by vixalien** [comment]
no. rebase and then in the `it.po` file, 

on the line that says `translator-credits` change it to the following:

```gettext
#. TRANSLATORS: eg. 'Translator Name <your.email@domain.com>' or 'Translator Name https://website.example/'
#: src/application.ts:349
msgid "translator-credits"
msgstr ""
"Your Names <your@email.com>"

```

**Review by vixalien — CHANGES_REQUESTED** [review]
please check the comment above

**Comment by vixalien** [comment]
please rebase and fix any merge conflicts

**Review by vixalien — APPROVED** [review]

**Pull request merged**
