### PR TITLE
New app icon

### PR DESCRIPTION
**Pull request by daudix-UFO**
The current icon is quite good but it doesn't follow the GNOME icon design guidelines, the app itself looks absolutely beautiful, but needs a nicer icon.

After some work and review from the GNOME Design Team I have a new icon, hope you will like it :D

image

### CODE REVIEW

**Comment by vixalien** [comment]
I agree that the app needs a new icon but personally I'm not quite sure about the looks of the new icon, since it looks more involved (what's the meaning of the light bulb for example, and usually one does not PIN sticky notes with a regular pin, they just stick onto any surface...)

in short, the new icon does not look like regular sticky notes so I'm not quite convinced lol

**Review by vixalien — COMMENTED** [review]
what changed?

**Comment by daudix-UFO** [comment]
> I agree that the app needs a new icon but personally I'm not quite sure about the looks of the new icon, since it looks more involved (what's the meaning of the light bulb for example, and usually one does not PIN sticky notes with a regular pin, they just stick onto any surface...)
> 
> in short, the new icon does not look like regular sticky notes so I'm not quite convinced lol

Well, I agree that pinned sticky note is a bit odd, but it were made mostly because [all notes apps](https://beta.flathub.org/en/apps/search/Note) use pretty much same concept of sticky note and a pen, so to be a bit different from them it have the pin, which is something new. I have seen it on one of the reference images.

image

In short, pin is here mostly to make icon unique.

About the bulb, it's purpose is to fill the note with something to not keep the icon boring, often ideas are visualized as a bulb, so it fits nicely, as one of the use cases for this app is to write down sudden ideas

If you want, we can iterate on the icon a bit ;)

> what changed?

Fixed the gradient on the pin :P

**Comment by vixalien** [comment]
I get it, but the icon feels so complicated (but unique). this means that people will not get the idea it conveys the first time Imo.

from the reference images, the one with the pin is better although if I must admit, the one with the paper clip is good too. the others look boring and normal...

what do you think?

**Comment by daudix-UFO** [comment]
idk if the icon is over complicated, imo it have a "normal" amount of detail, not sure if the paper clip will work, as to make it recognizable at 32x32 size it should be huge

**Comment by daudix-UFO** [comment]
image

**Comment by vixalien** [comment]
hmm I think it's kinda too large. I'm nitpicking at this point. maybe we need a third party to review this (preferably GNOME/Design team...) @exalm what do you think

**Comment by Exalm** [comment]
What do I have to do with design team?

**Comment by vixalien** [comment]
> What do I have to do with design team?

nevermind

**Review by vixalien — APPROVED** [review]

**Pull request merged**
