### PR TITLE
Add Translator Credits support

### PR DESCRIPTION
**Pull request by sabriunal**
More information: https://wiki.gnome.org/TranslationProject/DevGuidelines/Add%20translator%20credits

### CODE REVIEW

**Comment by vixalien** [comment]
please let me know if this can be merged before the 2 other PRs, and I'll do it right away!

**Comment by vixalien** [comment]
rebase & resolve confilcts

and tell me how exactly does this work...

**Comment by sabriunal** [comment]
Normally, you put this string in the about window it should read the translator informations from the po files. 

In this case it seems not working. You can close the PR.

**Comment by rffontenelle** [comment]
> and I'd like to know does this work. does each translator add their names or??

The translator should put its name/nick and, optionally, the email address. Then, in the Credits page, a Translated by will contain the info provided by this string.

For instance, see Nautilus/Files in pt_BR (the right-side icon is the translator's mail when provided):

Captura de tela de 2023-05-17 15-12-19

**Comment by vixalien** [comment]
@rffontenelle 

> The input should be something like:

that goes in the `.pot` file right

**Comment by rffontenelle** [comment]
> that goes in the `.pot` file right

Must go. The .pot file is made of strings extracted from the source code, translators-credit is no different.

I assume the pot in this PR commit was generated after adding the string to the code.

**Comment by vixalien** [comment]
alright. waiting for a rebase @sabriunal

and please add your name as a test so I can see if it works in the about menu

**Review by vixalien — APPROVED** [review]

**Pull request merged**
